local moduleTable = alya.modules.register("AutoClicker", "Clicks for you.", "COMBAT")
local mode      = moduleTable.addModeSetting("Mode", "", "Normal", "Normal", "Drag")
local cps       = moduleTable.addNumberSetting("CPS", "", 9, 0, 20, 0.01)
cps.setRangeEnabled(true)
cps.setSecondValue(11)
local dragTime  = moduleTable.addNumberSetting("Duration (MS)", "", 1200, 100, 2000, 100)
local dragDelay = moduleTable.addNumberSetting("Delay (MS)", "", 300, 100, 1000, 100)
cps.setVisibility(function() return mode.is("Normal") end)
dragTime.setVisibility(function() return mode.is("Drag") end)
dragDelay.setVisibility(function() return mode.is("Drag") end)
local createNormalMode = loadScript("/lua/modules/combat/autoclicker/normal.lua")
local createDragMode   = loadScript("/lua/modules/combat/autoclicker/drag.lua")
createNormalMode(moduleTable, mode, cps)
createDragMode(moduleTable, mode, cps, dragTime, dragDelay)
